version: "3.9"
services:
  test-py38:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8"
    command: pytest -v --tb=short

  test-py310:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
    command: pytest -v --tb=short

  test-py312:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    command: pytest -v --tb=short

  test-py313:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.13"
    command: pytest -v --tb=short
